name: CI/CD Todo List

on:
  push:
    branches: [ajout-workflow-cicd]
  pull_request:
    branches: [ajout-workflow-cicd]
  # workflow_dispatch:

jobs:
  unit-and-integration-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env: 
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: todolist_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        env: 
          DB_HOST: 127.0.0.1
          DB_USER: root
          DB_PASSWORD: rootpassword
          DB_NAME: todolist_db
          DB_DIALECT: mysql
          PORT: 3000
        run: |
          chmod +x ./node_modules/.bin/jest
          npm test

  docker-build-smoke-test:
    needs: unit-and-integration-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Docker image
        run: docker build -t my-todo-app .

      - name: Run container
        run: |
          docker run -d -p 3000:3000 --name app-container \
          -e DB_HOST=localhost \
          -e DB_USER=root \
          -e DB_PASSWORD=rootpassword \
          -e DB_NAME=todolist_db \
          my-todo-app
          
      - name: Wait for app to start
        run: sleep 10

      - name: HTTP Smoke Test
        run: |
          # On vérifie si l'app répond. Si curl reçoit une erreur, le job échoue.
          curl --silent --fail http://localhost:3000 || exit 1

      - name: Stop and cleanup
        if: always()
        run: docker stop app-container && docker rm app-container
