name: workflow filrouge test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: todolist_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root -prootpassword"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: rootpassword 
      DB_NAME: todolist_db
      DB_DIALECT: mysql
      NODE_ENV: dev

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instal des dépendances
        run: npm ci

      - name: en attente mysql 
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client
          for i in {1..40}; do
            mysql -h 127.0.0.1 -u root -prootpassword -e "SELECT 1" && break
            echo "MySQL non prêt, j'attends 3s..."
            sleep 3
          done

      - name: Test connexion MySQL 
        run: mysql -h 127.0.0.1 -u root -prootpassword -e "SHOW DATABASES;"

      - name: Run tests
        run: npm run test

  docker:
    runs-on: ubuntu-latest
    needs: test
    services:
      mysql: 
        image: mysql:8.0 
        env: 
          MYSQL_ROOT_PASSWORD: rootpassword 
          MYSQL_DATABASE: todolist_db 
        ports: 
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root -prootpassword" 
          --health-interval=10s 
          --health-timeout=5s
          --health-retries=5 

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Docker image
        run: docker build -t robot-battle .

      - name: Run container
        run: |
          docker run -d \
            -p 3000:3000 \
            -e DB_HOST=host.docker.internal \
            -e DB_USER=root \
            -e DB_PASSWORD=rootpassword \
            -e DB_NAME=todolist_db \
            -e DB_DIALECT=mysql \
            --add-host=host.docker.internal:host-gateway \
            --name app robot-battle

          for i in {1..10}; do
            curl -s http://localhost:3000 && echo "App is up!" && break
            echo "Waiting for app... (attempt $i)"
            sleep 3
          done

      - name: Smoke test HTTP
        run: curl -s http://localhost:3000

      - name: Stop container
        if: always()
        run: docker stop app || true